# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d0f8bcd7ff3eb6f42e8b4dc70560b0521a7248384cd566b1e916f943d65f527427c15d3149476aa52b22b4f18867c5459adb409e7fa8a0444e4a0a042f757b

test:
  secret_key_base: 546665b2d29b20d405887794364ce2cedfb5e4b2afa8f7b71280fc6589335451743e4cfc9af4c65051c4a034b6765230603f33ed86d22e39729f616b0839282c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
